name: Telegram Bot

on:
  workflow_dispatch:
  push:
    paths:
      - "bot.py"
      - "requirements.txt"
      - ".github/workflows/bot.yml"

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: Run Telegram bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: python bot.py
